# Makes sure that wheels have been uploaded for the latest Python version. #6
name: wheels
# When the 'permissions' key is specified, unspecified permission scopes (e.g.,
# actions, checks, etc.) are set to no access (none).
permissions:
  contents: read
on:
  schedule:
    # Run weekly (* is a special character in YAML, so quote the string)
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check Python version
      run: python --version

    - name: Update pip
      run: pip install --upgrade pip

    - name: Test (windows)
      if: matrix.os == 'windows-latest'
      # WARN: The install below doesn't specify a kmeans1d version. If an
      # earlier version of kmeans1d had wheels for the latest Python version,
      # that earlier kmeans1d version would be installed without failure. That
      # scenario is unlikely to occur.
      run: |
        pip install --only-binary :all: kmeans1d

    - name: Test (other)
      if: matrix.os != 'windows-latest'
      run: |
        VERSIONS="$(pip index --index-url https://test.pypi.org/simple/ versions kmeans1d)"
        LATEST="$(echo ${VERSIONS} | awk '/kmeans1d/ {print $2}' | sed 's/(\(.*\))/\1/')"
        pip install --only-binary :all: "kmeans1d==${LATEST}"
