# Makes sure that wheels have been uploaded for the latest Python version. #6
name: wheels
# When the 'permissions' key is specified, unspecified permission scopes (e.g.,
# actions, checks, etc.) are set to no access (none).
permissions:
  contents: read
on:
  schedule:
    # Run weekly (* is a special character in YAML, so quote the string)
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Check Python version
      run: python --version

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Test
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        $VERSIONS = pip index versions kmeans1d
        $LATEST = $VERSIONS[0] | ForEach-Object { $_ -replace 'kmeans1d \((.*)\)', '$1' }
        pip install --only-binary :all: "kmeans1d==$LATEST"
        if ($LASTEXITCODE -ne 0) { throw "error" }
